# Build settings
markdown: kramdown
#redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Site settings
title: "Rajath Kumar"
description: > # this means to ignore newlines until "email:"
   Things that I have done, learnt and thought about

email: rajathkumar.exe@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/desktop.png"

name: 'Rajath Kumar M.P'
author: 'Rajath Kumar M.P'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.rajathkumar.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/rajathkmp
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/rajathkumar.rk
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/rajathkumarmp
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://google.com/+rajathkumar
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
